
package com.dectechsolutions.instinct;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OnlineFraudCheck", targetNamespace = "http://dectechsolutions.com/Instinct", wsdlLocation = "http://localhost/Instinct_Fraud_Check_Web_Service_4.7.1_SPDB/InstinctFraudCheck.asmx?wsdl")
public class OnlineFraudCheck
    extends Service
{

    private final static URL ONLINEFRAUDCHECK_WSDL_LOCATION;
    private final static WebServiceException ONLINEFRAUDCHECK_EXCEPTION;
    private final static QName ONLINEFRAUDCHECK_QNAME = new QName("http://dectechsolutions.com/Instinct", "OnlineFraudCheck");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/Instinct_Fraud_Check_Web_Service_4.7.1_SPDB/InstinctFraudCheck.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ONLINEFRAUDCHECK_WSDL_LOCATION = url;
        ONLINEFRAUDCHECK_EXCEPTION = e;
    }

    public OnlineFraudCheck() {
        super(__getWsdlLocation(), ONLINEFRAUDCHECK_QNAME);
    }

    public OnlineFraudCheck(WebServiceFeature... features) {
        super(__getWsdlLocation(), ONLINEFRAUDCHECK_QNAME, features);
    }

    public OnlineFraudCheck(URL wsdlLocation) {
        super(wsdlLocation, ONLINEFRAUDCHECK_QNAME);
    }

    public OnlineFraudCheck(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ONLINEFRAUDCHECK_QNAME, features);
    }

    public OnlineFraudCheck(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OnlineFraudCheck(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OnlineFraudCheckSoap
     */
    @WebEndpoint(name = "OnlineFraudCheckSoap")
    public OnlineFraudCheckSoap getOnlineFraudCheckSoap() {
        return super.getPort(new QName("http://dectechsolutions.com/Instinct", "OnlineFraudCheckSoap"), OnlineFraudCheckSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineFraudCheckSoap
     */
    @WebEndpoint(name = "OnlineFraudCheckSoap")
    public OnlineFraudCheckSoap getOnlineFraudCheckSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://dectechsolutions.com/Instinct", "OnlineFraudCheckSoap"), OnlineFraudCheckSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ONLINEFRAUDCHECK_EXCEPTION!= null) {
            throw ONLINEFRAUDCHECK_EXCEPTION;
        }
        return ONLINEFRAUDCHECK_WSDL_LOCATION;
    }

}
