USE [InstinctDRC]
GO

CREATE NONCLUSTERED INDEX [IX_T01_IND_CUST_BIZ_INFO_P_Cert_ID] ON [dbo].[T01_IND_CUST_BIZ_INFO_P]
(
	[Cert_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_T01_IND_ERA_PAY_STAT_P_CORE_CUST_ID] ON [dbo].[T01_IND_ERA_PAY_STAT_P]
(
	[CORE_CUST_ID] ASC
)
INCLUDE
(
	[IS_AGENT_DISTR_CUST]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_RW_IND_BASIC_INFO_TAB_Cert_ID] ON [dbo].[RW_IND_BASIC_INFO_TAB]
(
	[Cert_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_T01_CUST_RELATIVE_G_Cust_ID] ON [dbo].[T01_CUST_RELATIVE_G]
(
	[Cust_ID] ASC
)
INCLUDE
(
	[Rela_Ship]
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_QZZC_UBNK_CRDT_INFO_Cust_ID] ON [dbo].[QZZC_UBNK_CRDT_INFO]
(
	[Cust_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_QZZC_APPC_ENT_INFO_Appc_Cert_ID_Appc_Cert_Type] ON [dbo].[QZZC_APPC_ENT_INFO]
(
	[Appc_Cert_ID] ASC
)
INCLUDE
(
Appc_Cert_Type
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


