
package com.dectechsolutions.watch;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InstinctWatchCheck", targetNamespace = "http://dectechsolutions.com/Instinct", wsdlLocation = "http://localhost/InstinctWatchWeb/InstinctWatchCheck.asmx?wsdl")
public class InstinctWatchCheck
    extends Service
{

    private final static URL INSTINCTWATCHCHECK_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.dectechsolutions.watch.InstinctWatchCheck.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.dectechsolutions.watch.InstinctWatchCheck.class.getResource(".");
            url = new URL(baseUrl, "http://localhost/InstinctWatchWeb/InstinctWatchCheck.asmx?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/InstinctWatchWeb/InstinctWatchCheck.asmx?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INSTINCTWATCHCHECK_WSDL_LOCATION = url;
    }

    public InstinctWatchCheck(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InstinctWatchCheck() {
        super(INSTINCTWATCHCHECK_WSDL_LOCATION, new QName("http://dectechsolutions.com/Instinct", "InstinctWatchCheck"));
    }
    
    public InstinctWatchCheck(URL wsdlLocation) {
        super(wsdlLocation, new QName("http://dectechsolutions.com/Instinct", "InstinctWatchCheck"));
    }

    /**
     * 
     * @return
     *     returns InstinctWatchCheckSoap
     */
    @WebEndpoint(name = "InstinctWatchCheckSoap")
    public InstinctWatchCheckSoap getInstinctWatchCheckSoap() {
        return super.getPort(new QName("http://dectechsolutions.com/Instinct", "InstinctWatchCheckSoap"), InstinctWatchCheckSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InstinctWatchCheckSoap
     */
    @WebEndpoint(name = "InstinctWatchCheckSoap")
    public InstinctWatchCheckSoap getInstinctWatchCheckSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://dectechsolutions.com/Instinct", "InstinctWatchCheckSoap"), InstinctWatchCheckSoap.class, features);
    }

}
