'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
'
Namespace InstinctAction
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="InstinctActionWebServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InstinctActionWebService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private InstinctActionStringReturnOperationCompleted As System.Threading.SendOrPostCallback
        
        Private InstinctActionXMLStringReturnOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Instinct.Windows.Service.ActionService.My.MySettings.Default.Instinct_Windows_Service_ActionService_InstinctAction_InstinctActionWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event InstinctActionStringReturnCompleted As InstinctActionStringReturnCompletedEventHandler
        
        '''<remarks/>
        Public Event InstinctActionXMLStringReturnCompleted As InstinctActionXMLStringReturnCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InstinctActionStringReturn", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InstinctActionStringReturn(ByVal actionString As String) As String
            Dim results() As Object = Me.Invoke("InstinctActionStringReturn", New Object() {actionString})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InstinctActionStringReturnAsync(ByVal actionString As String)
            Me.InstinctActionStringReturnAsync(actionString, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InstinctActionStringReturnAsync(ByVal actionString As String, ByVal userState As Object)
            If (Me.InstinctActionStringReturnOperationCompleted Is Nothing) Then
                Me.InstinctActionStringReturnOperationCompleted = AddressOf Me.OnInstinctActionStringReturnOperationCompleted
            End If
            Me.InvokeAsync("InstinctActionStringReturn", New Object() {actionString}, Me.InstinctActionStringReturnOperationCompleted, userState)
        End Sub
        
        Private Sub OnInstinctActionStringReturnOperationCompleted(ByVal arg As Object)
            If (Not (Me.InstinctActionStringReturnCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InstinctActionStringReturnCompleted(Me, New InstinctActionStringReturnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InstinctActionXMLStringReturn", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function InstinctActionXMLStringReturn(ByVal actionString As String) As String
            Dim results() As Object = Me.Invoke("InstinctActionXMLStringReturn", New Object() {actionString})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub InstinctActionXMLStringReturnAsync(ByVal actionString As String)
            Me.InstinctActionXMLStringReturnAsync(actionString, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub InstinctActionXMLStringReturnAsync(ByVal actionString As String, ByVal userState As Object)
            If (Me.InstinctActionXMLStringReturnOperationCompleted Is Nothing) Then
                Me.InstinctActionXMLStringReturnOperationCompleted = AddressOf Me.OnInstinctActionXMLStringReturnOperationCompleted
            End If
            Me.InvokeAsync("InstinctActionXMLStringReturn", New Object() {actionString}, Me.InstinctActionXMLStringReturnOperationCompleted, userState)
        End Sub
        
        Private Sub OnInstinctActionXMLStringReturnOperationCompleted(ByVal arg As Object)
            If (Not (Me.InstinctActionXMLStringReturnCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent InstinctActionXMLStringReturnCompleted(Me, New InstinctActionXMLStringReturnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub InstinctActionStringReturnCompletedEventHandler(ByVal sender As Object, ByVal e As InstinctActionStringReturnCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InstinctActionStringReturnCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")>  _
    Public Delegate Sub InstinctActionXMLStringReturnCompletedEventHandler(ByVal sender As Object, ByVal e As InstinctActionXMLStringReturnCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class InstinctActionXMLStringReturnCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
