SET ANSI_PADDING ON

CREATE NONCLUSTERED INDEX [IX_Staging_T01_IND_CUST_CORE_INFO_P_CUST_ID_From_System] ON [dbo].[Staging_T01_IND_CUST_CORE_INFO_P]
(
	[Cust_ID] ASC
)
INCLUDE ( 	[Inputdate],
	[From_System]) WITH (SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]

CREATE STATISTICS [STAT_Staging_T01_IND_CUST_CORE_INFO_P] ON [dbo].[Staging_T01_IND_CUST_CORE_INFO_P]([Fax_Id])

